[WebServer]
username = "km3net"
password = "pyrosoma"

[DOMRates]
lowest_rate = 0.1
highest_rate = 750

[PMTRates]
lowest_rate = 10
highest_rate = 20000
hrv_ratio_threshold = 0.85

[TriggerRate]
interval = 300
with_minor_ticks = true

[TriggerMap]
max_events = 5000

[ZTPlot]
min_dus = 1
min_doms = 8
ytick_distance = 25


[CalibrateAHRS]
time_range = 72

[LocalDBService]
filename = "data/monitoring.sqlite3"

[ELOGService]
password = "pyrosoma"

[Alerts]
botname = "monitoring_bci"
password = "pyrosoma"
channel = "operations_fr"
operators = [ "a_enzenhoefer", "tamasgal"]
